#
# Copyright 2020 The dNation Kubernetes Monitoring Stack Authors. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

{{- if and .Values.thanos.enabled .Values.thanosQueryEnvoySidecar.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.thanosQueryEnvoySidecar.service.name }}
  {{- with .Values.thanosQueryEnvoySidecar.service.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  {{- range .Values.thanosQueryEnvoySidecar.config }}
    - name: http-{{ .name }}
      protocol: TCP
      port: {{ .listenPort }}
      targetPort: {{ .listenPort }}
  {{- end }}
  {{- with .Values.thanosQueryEnvoySidecar.service.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  type: ClusterIP
{{- end }}
