{{- if and .Values.thanos.enabled .Values.thanosStorage }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.thanosStorage.secret.name }}
  namespace: {{ include "k8s-monitoring-stack.namespace" $ }}
  labels:
    app: {{ include "k8s-monitoring-stack.name" $ }}
type: Opaque
data:
  # {{ .Values.thanosStorage.secret.key }}: {{ .Values.thanosStorage.config | toYaml | b64enc | quote }}
  {{ tpl .Values.thanosStorage.secret.key $ }}: {{ tpl .Values.thanosStorage.config $ | b64enc | quote }}
{{- end }}