apiVersion: v2
name: k8s-m8g-stack
version: 1.0.22
appVersion: 1.0.11  # k8s-m8g
description: An umbrella helm chart for Kubernetes monitoring based on kube-prometheus-stack, loki-stack and k8s-m8g.
keywords:
- kubernetes
- monitoring
- prometheus
- grafana
- loki
home: https://git.ifne.eu/dnation/k8s-m8g-stack
sources:
- https://git.ifne.eu/dnation/k8s-m8g-stack
dependencies:
- name: kube-prometheus-stack
  version: "10.1.*"
  repository: https://prometheus-community.github.io/helm-charts
  condition: kube-prometheus-stack.enabled
- name: loki-stack
  version: "0.41.*"
  repository: https://grafana.github.io/loki/charts
  condition: loki-stack.enabled
- name: k8s-m8g
  version: "1.0.*"
  repository: https://nexus.ifne.eu/repository/ifne-helm-public/
  condition: k8s-m8g.enabled
icon: https://storage.googleapis.com/ifne.eu/public/icons/dnation_k8sm8g.png
maintainers:
- name: dNation
  email: admin@dNation.tech
