apiVersion: v2
name: dnation-kubernetes-monitoring-stack
version: 1.1.1
appVersion: 1.1.0  # dnation-kubernetes-monitoring
description: An umbrella helm chart for Kubernetes monitoring based on kube-prometheus-stack, loki-stack and dnation-kubernetes-monitoring.
keywords:
- dnation
- kubernetes
- monitoring
- prometheus
- grafana
- loki
home: https://dnation.cloud
sources:
- https://github.com/dNationCloud/kubernetes-monitoring-stack
dependencies:
- name: kube-prometheus-stack
  version: "13.9.*"
  repository: https://prometheus-community.github.io/helm-charts
  condition: kube-prometheus-stack.enabled
- name: loki-stack
  version: "2.3.*"
  repository: https://grafana.github.io/helm-charts
  condition: loki-stack.enabled
- name: dnation-kubernetes-monitoring
  version: "1.1.*"
  repository: https://dnationcloud.github.io/helm-hub
  condition: dnation-kubernetes-monitoring.enabled
icon: https://cdn.ifne.eu/public/icons/dnation_k8sm8g.png
maintainers:
- name: dNation
  email: cloud@dNation.cloud
