#
# Copyright 2020 The dNation Kubernetes Monitoring Stack Authors. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v2
name: dnation-kubernetes-monitoring-stack
version: 2.2.0
appVersion: 2.2.0  # dnation-kubernetes-monitoring
description: An umbrella helm chart for Kubernetes monitoring based on kube-prometheus-stack, thanos, loki, loki-distributed, promtail and dnation-kubernetes-monitoring.
keywords:
- dnation
- kubernetes
- monitoring
- logging
- prometheus
- grafana
- loki
- thanos
home: https://dnation.cloud
sources:
- https://github.com/dNationCloud/kubernetes-monitoring-stack
dependencies:
- name: kube-prometheus-stack
  version: "39.6.*"
  repository: https://prometheus-community.github.io/helm-charts
  condition: kube-prometheus-stack.enabled
- name: thanos
  version: "11.4.*"
  repository: https://charts.bitnami.com/bitnami
  condition: thanos.enabled
- name: loki
  version: "2.9.*"
  repository: https://grafana.github.io/helm-charts
  condition: loki.enabled
- name: loki-distributed
  version: "0.42.*"
  repository: https://grafana.github.io/helm-charts
  condition: loki-distributed.enabled
- name: promtail
  version: "3.11.*"
  repository: https://grafana.github.io/helm-charts
  condition: promtail.enabled
- name: dnation-kubernetes-monitoring
  version: "2.2.*"
  repository: https://dnationcloud.github.io/helm-hub
  condition: dnation-kubernetes-monitoring.enabled

icon: https://cdn.ifne.eu/public/icons/dnation_k8sm8g.png
maintainers:
- name: dNation
  email: cloud@dNation.cloud
