apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
metricsBindAddress: 0.0.0.0:10249
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
etcd:
  local:
    extraArgs:
      listen-metrics-urls: http://0.0.0.0:2381
networking:
  podSubnet: 10.244.0.0/16
scheduler:
  extraArgs:
    port: "10251"
    bind-address: 0.0.0.0
controllerManager:
  extraArgs:
    port: "10252"
    bind-address: 0.0.0.0
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  ignorePreflightErrors:
  - NumCPU
