thanosStorage:
  # More details about supported storage types and config options can be found here: https://thanos.io/tip/thanos/storage.md/
  config: |-
    type: S3
    config:
      endpoint: "<api-of-the-S3>"
      bucket: "<workload-bucket-name>"
      access_key: "<access-key>"
      secret_key: "<secret-key>"
      insecure: false
      signature_version2: true
      part_size: 0

loki-stack:
  promtail:
    extraArgs:
      - -client.external-labels=cluster=workload-cluster

thanos:
  global:
    storageClass: <storage-class>
  query:
    logLevel: debug
    ingress:
      enabled: false # disabled for http
      grpc:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
          ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/grpc-backend: "true"
          nginx.ingress.kubernetes.io/auth-tls-secret: "default/thanos-ca-secret"
          nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
        hostname: <url of exposed query component on remote workload cluster>
        tls: false
        extraTls:
          - hosts:
              - <url of exposed query component on remote workload cluster>
            secretName: <secret-name-by-server-certificate>

kube-prometheus-stack:

  prometheus:
    prometheusSpec:
      # !IMPORTANT: each cluster must have prometheus external label 'cluster' with unique value.
      # This will be used as cluster discriminator when metrics are aggregated on observer cluster.
      externalLabels:
        cluster: "workload-cluster"
