# Configuration for loki-stack chart
# https://github.com/grafana/loki/tree/master/production/helm/loki-stack
loki-stack:
  enabled: true
  loki:
    persistence:
      enabled: false
  # Grafana deployment is managed by kube-prometheus-stack chart
  grafana:
    enabled: false
    sidecar:
      datasources:
        enabled: false

# Configuration for kube-prometheus-stack chart
# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
kube-prometheus-stack:
  enabled: true
  nameOverride: prom-op
  grafana:
    adminUser: "admin"
    adminPassword: "pass"
    defaultDashboardsEnabled: false
    extraConfigmapMounts:
    - name: dnation-logo
      mountPath: /usr/share/grafana/public/img/grafana_icon.svg
      subPath: dnation.svg
      configMap: dnation-logo
      readOnly: true
    sidecar:
      dashboards:
        label: grafana_dashboard
        folder: /var/lib/grafana/dashboards/k8s-m8g
        provider:
          name: 'K8sM8g'
          folder: 'K8sM8g'
          disableDeletion: false
          allowUiUpdates: true
          editable: true
      datasources:
        label: grafana_datasource
        defaultDatasourceEnabled: false
    additionalDataSources:
    - name: cluster-metrics
      isDefault: false
      type: prometheus
      url: "{{ .Release.Name }}-prom-op-prometheus:9090"
    - name: cluster-logs
      isDefault: false
      type: loki
      url: "{{ .Release.Name }}-loki:3100"
    - name: cluster-alertmanager
      isDefault: false
      type: camptocamp-prometheus-alertmanager-datasource
      url: "{{ .Release.Name }}-prom-op-alertmanager:9093"
      jsonData:
        severity_critical: critical
        severity_high: high
        severity_warning: warning
        severity_info: info
    plugins:
    - camptocamp-prometheus-alertmanager-datasource
    - grafana-polystat-panel

  alertmanager:
    config:
      route:
        receiver: 'null'
        routes:
        - match:
            alertname: Watchdog
          receiver: 'null'
      inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname']
