{{- range .Values.extraCertificates }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .name }}
  namespace: {{ include "k8s-monitoring-stack.namespace" $ }}
  labels:
    app: {{ include "k8s-monitoring-stack.name" $ }}
spec:
  secretName: {{ .secretName }}
  issuerRef:
    name: {{ .issuer }}
  commonName: {{ .commonName }}
  dnsNames:
  {{- range .hosts }}
  - {{ . }}
  {{- end }}
---
{{- end }}
