{{- range .Values.extraSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ include "k8s-monitoring-stack.namespace" $ }}
  labels:
    app: {{ include "k8s-monitoring-stack.name" $ }}
type: Opaque
data:
  {{ .data | toYaml | b64enc | quote }}
---
{{- end }}
