#  Copyright 2020 The K8s-m8g-stack Authors. All Rights Reserved.
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "monitoring.fullname" $) "dnation-node.rules" | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ default "kube-prometheus-stack" (index .Values "kube-prometheus-stack" "nameOverride") | trunc 50 | trimSuffix "-" }}
    release: {{ $.Release.Name }}
spec:
  groups:
  - name: dnation-node.rules
    rules:
    - alert: GreenRedMonitoringCPUAvgHigh
      annotations:
        message: 'High Avg CPU Cluster Utilization {{`{{`}} $value {{`}}`}}%'
      expr: |-
        round((1 - (avg(irate(node_cpu_seconds_total{job="node-exporter",mode="idle"}[5m])))) * 100) >= 90
      for: 5m
      labels:
        severity: critical
    - alert: GreenRedMonitoringCPUOverallHigh
      annotations:
        message: '"{{`{{`}} $labels.nodename {{`}}`}}": High CPU Utilization {{`{{`}} $value {{`}}`}}%'
      expr: |-
        {{ include "host.expr.overall.cpu" . }} >= 90
      for: 5m
      labels:
        severity: critical
    - alert: GreenRedMonitoringCPUAvgHigh
      annotations:
        message: 'High Avg CPU Cluster Utilization {{`{{`}} $value {{`}}`}}%'
      expr: |-
        round((1 - (avg(irate(node_cpu_seconds_total{job="node-exporter",mode="idle"}[5m])))) * 100) >= 75
      for: 5m
      labels:
        severity: warning
    - alert: GreenRedMonitoringCPUOverallHigh
      annotations:
        message: '"{{`{{`}} $labels.nodename {{`}}`}}": High CPU Utilization {{`{{`}} $value {{`}}`}}%'
      expr: |-
        {{ include "host.expr.overall.cpu" . }} >= 75
      for: 5m
      labels:
        severity: warning
    - alert: GreenRedMonitoringRAMAvgHigh
      annotations:
        message: 'High Avg RAM Cluster Utilization {{`{{`}} $value {{`}}`}}%'
      expr: |-
        round((1 - sum(node_memory_MemAvailable_bytes{job="node-exporter"}) / sum(node_memory_MemTotal_bytes{job="node-exporter"})) * 100) >= 90
      for: 5m
      labels:
        severity: critical
    - alert: GreenRedMonitoringRAMOverallHigh
      annotations:
        message: '"{{`{{`}} $labels.nodename {{`}}`}}": High RAM Utilization {{`{{`}} $value {{`}}`}}%'
      expr: |-
        {{ include "host.expr.overall.ram" . }} >= 90
      for: 5m
      labels:
        severity: critical
    - alert: GreenRedMonitoringRAMAvgHigh
      annotations:
        message: 'High Avg RAM Cluster Utilization {{`{{`}} $value {{`}}`}}%'
      expr: |-
        round((1 - sum(node_memory_MemAvailable_bytes{job="node-exporter"}) / sum(node_memory_MemTotal_bytes{job="node-exporter"})) * 100) >= 75
      for: 5m
      labels:
        severity: warning
    - alert: GreenRedMonitoringRAMOverallHigh
      annotations:
        message: '"{{`{{`}} $labels.nodename {{`}}`}}": High RAM Utilization {{`{{`}} $value {{`}}`}}%'
      expr: |-
        {{ include "host.expr.overall.ram" . }} >= 75
      for: 5m
      labels:
        severity: warning
    - alert: GreenRedMonitoringDiskAvgHigh
      annotations:
        message: 'High Avg Disk Cluster Utilization {{`{{`}} $value {{`}}`}}%'
      expr: |-
        round(avg((sum(node_filesystem_size_bytes{job="node-exporter", device!="rootfs"}) by (device) - sum(node_filesystem_free_bytes{job="node-exporter", device!="rootfs"}) by (device)) / (sum(node_filesystem_size_bytes{job="node-exporter", device!="rootfs"}) by (device) - sum(node_filesystem_free_bytes{job="node-exporter", device!="rootfs"}) by (device) + sum(node_filesystem_avail_bytes{job="node-exporter", device!="rootfs"}) by (device)) * 100)) >= 90
      for: 5m
      labels:
        severity: critical
    - alert: GreenRedMonitoringDiskOverallHigh
      annotations:
        message: '"{{`{{`}} $labels.nodename {{`}}`}}": High Disk Utilization {{`{{`}} $value {{`}}`}}%'
      expr: |-
        {{ include "host.expr.overall.disk" . }} >= 90
      for: 5m
      labels:
        severity: critical
    - alert: GreenRedMonitoringDiskAvgHigh
      annotations:
        message: 'High Avg Disk Cluster Utilization {{`{{`}} $value {{`}}`}}%'
      expr: |-
        round(avg((sum(node_filesystem_size_bytes{job="node-exporter", device!="rootfs"}) by (device) - sum(node_filesystem_free_bytes{job="node-exporter", device!="rootfs"}) by (device)) / (sum(node_filesystem_size_bytes{job="node-exporter", device!="rootfs"}) by (device) - sum(node_filesystem_free_bytes{job="node-exporter", device!="rootfs"}) by (device) + sum(node_filesystem_avail_bytes{job="node-exporter", device!="rootfs"}) by (device)) * 100)) >= 75
      for: 5m
      labels:
        severity: warning
    - alert: GreenRedMonitoringDiskOverallHigh
      annotations:
        message: '"{{`{{`}} $labels.nodename {{`}}`}}": High Disk Utilization {{`{{`}} $value {{`}}`}}%'
      expr: |-
        {{ include "host.expr.overall.disk" . }} >= 75
      for: 5m
      labels:
        severity: warning
    - alert: GreenRedMonitoringNetworkErrorsHigh
      annotations:
        message: '"{{`{{`}} $labels.nodename {{`}}`}}": High Network Errors Count {{`{{`}} $value {{`}}`}}'
      expr: |-
        {{ include "host.expr.overall.network" . }} >= 15
      for: 5m
      labels:
        severity: critical
    - alert: GreenRedMonitoringNetworkErrorsHigh
      annotations:
        message: '"{{`{{`}} $labels.nodename {{`}}`}}": High Network Errors Count {{`{{`}} $value {{`}}`}}'
      expr: |-
        {{ include "host.expr.overall.network" . }} >= 10
      for: 5m
      labels:
        severity: warning
