{{- if .Values.dNation }}
{{- if .Values.dNation.certificate }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: dnation-certificate
  namespace: {{ include "k8s-monitoring-stack.namespace" . }}
  labels:
    app: {{ include "k8s-monitoring-stack.name" . }}
spec:
  secretName: {{ .Values.dNation.certificate.secretName }}
  issuerRef:
    name: {{ .Values.dNation.certificate.issuer }}
  commonName: {{ .Values.dNation.certificate.commonName }}
  dnsNames:
  {{- range .Values.dNation.certificate.hosts }}
  - {{ . }}
  {{- end }}
{{- end }}
{{- end }}
