#
# Copyright 2020 The dNation Kubernetes Monitoring Stack Authors. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: dnation-home
  namespace: {{ include "k8s-monitoring-stack.namespace" . }}
  labels:
    app: {{ include "k8s-monitoring-stack.name" . }}
data:
  home.json: |-
    {
      "links": [],
      "panels": [
        {
          "datasource": null,
          "gridPos": {
            "h": 3,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 1,
          "title": "",
          "transparent": false,
          "type": "welcome"
        },
        {
          "datasource": null,
          "folderId": 0,
          "gridPos": {
            "h": 15,
            "w": 24,
            "x": 0,
            "y": 4
          },
          "headings": true,
          "id": 3,
          "limit": 100,
          "links": [],
          "options": {},
          "query": "",
          "recent": true,
          "search": false,
          "starred": true,
          "tags": [],
          "title": "Dashboards",
          "type": "dashlist"
        }
      ],
      "schemaVersion": 22,
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {
        "hidden": true,
        "refresh_intervals": [ "5s", "10s", "30s", "1m", "5m", "15m", "30m", "1h", "2h", "1d" ],
        "time_options": [ "5m", "15m", "1h", "6h", "12h", "24h", "2d", "7d", "30d" ],
        "type": "timepicker"
      },
      "timezone": "browser",
      "title": "Home"
    }
