{{- if .Values.dNation }}
{{- if .Values.dNation.issuer }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.dNation.issuer.name }}
  namespace: {{ include "k8s-monitoring-stack.namespace" . }}
  labels:
    app: {{ include "k8s-monitoring-stack.name" . }}
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ .Values.dNation.issuer.email }}
    privateKeySecretRef:
      name: {{ .Values.dNation.issuer.name }}
    # Enable the HTTP-01 challenge provider
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector: {}
      http01:
        ingress:
          class: nginx
{{- end }}
{{- end }}
