{{ if .Values.openshift.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-prometheus-admission
  namespace: {{ $.Release.Namespace }}
  # The service account must be created before kube-prometheus admission webhook
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade, post-delete
{{ end }}
