{{ if and (.Values.openshift.enabled) (not .Values.openshift.existingSecurityContextConstraints) }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade, post-delete
  name: {{.Release.Namespace}}-{{ .Release.Name }}-scc
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities: []
defaultAddCapabilities: null
fsGroup:
  type: RunAsAny
groups:
  - system:cluster-admins
readOnlyRootFilesystem: false
requiredDropCapabilities:
  - 'AUDIT_CONTROL'
  - 'AUDIT_WRITE'
  - 'BLOCK_SUSPEND'
  - 'CHOWN'
  - 'DAC_OVERRIDE'
  - 'DAC_READ_SEARCH'
  - 'FOWNER'
  - 'FSETID'
  - 'IPC_LOCK'
  - 'IPC_OWNER'
  - 'KILL'
  - 'LEASE'
  - 'LINUX_IMMUTABLE'
  - 'MAC_ADMIN'
  - 'MAC_OVERRIDE'
  - 'MKNOD'
  - 'NET_ADMIN'
  - 'NET_BIND_SERVICE'
  - 'NET_BROADCAST'
  - 'NET_RAW'
  - 'SETFCAP'
  - 'SETGID'
  - 'SETPCAP'
  - 'SETUID'
  - 'SYS_ADMIN'
  - 'SYS_BOOT'
  - 'SYS_CHROOT'
  - 'SYSLOG'
  - 'SYS_MODULE'
  - 'SYS_NICE'
  - 'SYS_PACCT'
  - 'SYS_PTRACE'
  - 'SYS_RAWIO'
  - 'SYS_RESOURCE'
  - 'SYS_TIME'
  - 'SYS_TTY_CONFIG'
  - 'WAKE_ALARM'
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
users: []
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
  - hostPath
{{ end }}
