{{ if .Values.openshift.enabled }}
{{ range .Values.openshift.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ . }}
  namespace: {{ $.Release.Namespace }}
{{ end }}
{{ end }}
