#
# Copyright 2020 The dNation Kubernetes Monitoring Stack Authors. All Rights Reserved.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Values for dNation Kubernetes Monitoring Stack to be used in addition
# to default values.yaml for replacing default monolithic version of loki
# with loki-distributed.
# Declare variables to be passed into helm chart dependencies.

############################################## WARNING ###############################################################
##
## DEPRECATED VALUES
##
## The following values are deprecated and will be removed in a future version of the helm chart!
############################################## WARNING ##############################################################
## Configure additional grafana datasources
grafanaDatasourcesAsConfigMap:
  cluster-logs:
    - name: cluster-logs
      isDefault: false
      type: loki
      url: "http://{{ .Release.Name }}-loki-gateway"

loki:
  enabled: false

loki-distributed:
  enabled: true
  nameOverride: loki

  # enable servicemonitors for prometheus scraping
  serviceMonitor:
    enabled: true
    # relabel job to name of loki component
    relabelings:
      - targetLabel: component
        sourceLabels:
          - __meta_kubernetes_service_label_app_kubernetes_io_component
      - targetLabel: job
        sourceLabels:
          - __meta_kubernetes_service_label_app_kubernetes_io_name
        replacement: loki

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      # loki-distributed doesn't have proper labels so it doesn't match default prometheus serviceMonitorSelector
      # https://stackoverflow.com/questions/69466567/why-is-it-that-my-prometheus-operator-servicemonitor-needs-a-release-label-to
      serviceMonitorSelectorNilUsesHelmValues: false
